### ISSUE TITLE
Change number of colors in Loopy from 3 to 4? 

### ISSUE THREAD

**Issue by stephaniehicks** [chaichontat/loopy-browser#39]
I've been learning about fluorescent channels and talking with Stephanie Page and it seem it's fairly standard to use 4 channels (and 6 is less common). Would it be possible to modify the browser to show 4 colors (blue, green, red and far red)? The concern is someone who standardly has 4 channels in their image would have to toggle between the 3 colors currently there. 

What are your thoughts? Is this possible?

**Comment by chaichontat** [comment]
It's possible, although in an imperfect manner. I'll need to find alternative colormaps and allow the user to select them.
