### ISSUE TITLE
Loopybrowser doesn't work in Safari and Firefox

### ISSUE THREAD

**Issue by boyiguo1** [chaichontat/loopy-browser#48]
Thanks for providing this amazing tool!

As I was experimenting with Loopybrowser, I realize that Loopybrowser doesn't work with Safari and Firefox, in the sense that it loads up the UI elements but not the image. 
![Screen Shot 2022-09-29 at 2 30 53 PM](https://user-images.githubusercontent.com/16565218/193114072-5b5905e6-d1e2-4b2f-8cbe-61c0c7019276.png)

Just make sure, I turned off my browser add-ons (e.g. ad blockers) in case they interfere.

The error message I saw associated with the image not loading up is 
![Screen Shot 2022-09-29 at 2 33 43 PM](https://user-images.githubusercontent.com/16565218/193114500-35850d3a-f226-4c89-873c-5c85b5e0293a.png)

Without background in web programming, I wonder if CORS plays a role in this problem. After all, I didn't receive the same error when I use Google Chrome as recommended. 

Here is the link related to the error `Reason: CORS header ‘Access-Control-Allow-Origin’ missing). Status code: 200.` https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS/Errors/CORSMissingAllowOrigin

Also, as a quick patch-up solution, it might be helpful for users to see in the prompt up message `If no image load up, please use Chrome.`

Again, thank you very much for your awesome work!

**Comment by chaichontat** [comment]
Hi! The most recent version has a popup saying that the Browser won't work well in anything not Chrome. The CORS problem is not the only one. Several of the convenient APIs I used are also Chromium only. As this is quite a niche app, I think that expanding support is not worth it for now.

**Comment by boyiguo1** [comment]
Thanks for the feedback. My suggestion as a user is to be more explicit about the warning message. 
"Loopy Browser is optimized for Google Chrome. Please use Google Chrome for the best experience." I would understand this message as Loopy browser would still work, just slower or some functionality would not work. I would not think the image would not load up at all. 

Also, as I am writing, I just realize this is probably a problem with example data, but not loading up new data, right?

Personally, I would prefer some language like "If you have experience loading up the example image, please use Chrome."

Anyway, I appreciate your hard work. Thanks!

**Comment by chaichontat** [comment]
Ok, thanks! The image does appear now though.
