### ISSUE TITLE
Checking link to https://github.com/LieberInstitute/spatialDLPFC IF (SPG) data

### ISSUE THREAD

**Issue by lcolladotor** [chaichontat/loopy-browser#72]
Hi,

From the README.md, there's a link to https://loopybrowser.com/from?url=libd-spatial-dlpfc-loopy.s3.amazonaws.com/VisiumIF/&s=sample. I would have expected that link to contain the Visium SPG (IF) data from https://github.com/LieberInstitute/spatialDLPFC but I don't see it. Is that the right link?

Thanks!

**Comment by chaichontat** [comment]
It's https://loopybrowser.com/from?url=data2.loopybrowser.com/HumanPilot/&s=151507&s=151508&s=151509&s=151510&s=151669&s=151670&s=151671&s=151672&s=151673&s=151674&s=151675&s=151676 at "Show Visium Data" on the main page.

**Comment by lcolladotor** [comment]
Thanks!
